name: checkov

on: [pull_request]
permissions: read-all

jobs:
  checkov:
    permissions:
      contents: read
      actions: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli
